sudo: false
language: c

addons:
  apt:
    packages:
    - libgmp-dev

compiler:
  - gcc
  - clang

script:
  - dpkg -L libgmp-dev
  - make gmp
  - $CC -Wall gmp.c -o gmp -lgmp
  - $CC -Wall -lgmp gmp.c -o gmp
  - make clean

